FROM rust:latest

RUN apt-get update && \
    apt-get install sudo -y

RUN  rustup component add rustfmt

RUN useradd -s /bin/bash -m developer && \
    chmod u+s /sbin/unix_chkpwd && \
    echo "developer:developer" | chpasswd && \
    groupadd docker && \
    usermod -aG docker developer && \
    usermod -aG sudo developer

USER developer